import copy, importlib.util
from pathlib import Path
spec=importlib.util.spec_from_file_location('m', Path(__file__).with_name('final_real_observation_authorization_consumption.py')); m=importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
H=m._h
NOW='2026-08-22T07:50:00Z'
SRC='a'*64; SCOPE={'method':'GET','request_count':1,'required_environment':'production','target_fingerprint':'target-1','credentials_allowed':False,'action_enabled':False}; SH=H(SCOPE)
limits={'scheme':'https','tls_required':True,'method':'GET','max_network_requests':1,'allow_redirects':False,'max_redirects':0,'allowed_content_types':['application/json'],'max_response_bytes':1048576,'credentials_allowed':False,'action_enabled':False}
p0={'schema_version':1,'mode':m.PACKET_MODE,'request_state':'ready_for_fresh_explicit_final_real_observation_decision','requested_at':'2026-08-22T07:45:00Z','expires_at':'2026-08-22T07:55:00Z','ttl_seconds':600,'adapter_id':'payan_readonly','target_fingerprint':'target-1','exact_scope_sha256':SH,'exact_scope':SCOPE,'implementation_source_sha256':SRC,'hostname':'example.com','pinned_addresses':['93.184.216.34'],'policy_evidence_sha256':'1'*64,'dns_evidence_sha256':'2'*64,'transport_contract_sha256':'3'*64,'transport_limits':limits,'remaining_prerequisites':{'fresh_explicit_final_human_decision_bound_to_packet_hash':True,'revalidate_packet_and_safety_evidence_freshness_at_execution':True,'revalidate_dns_pinning_and_anti_rebinding_at_execution':True,'network_capable_adapter_still_unreachable':True},'explicit_final_human_decision_required':True,'final_real_observation_authorized':False,'network_capable_adapter_reachable':False,'adapter_invoked':False,'transport_enabled':False,'network_enabled':False,'network_calls_performed':False,'credentials_allowed':False,'task_acceptance_enabled':False,'submission_enabled':False,'execution_enabled':False,'value_movement_enabled':False,'packet_is_execution_token':False}
p={**p0,'final_real_observation_review_packet_sha256':H(p0)}
a0={'schema_version':1,'mode':m.AUTH_MODE,'authorization_state':'authorized_single_use_not_consumed','issued_at':'2026-08-22T07:49:00Z','expires_at':'2026-08-22T07:52:00Z','single_use':True,'consumed':False,'decision_id':'d1','final_real_observation_decision_sha256':'4'*64,'final_real_observation_review_packet_sha256':p['final_real_observation_review_packet_sha256'],'adapter_id':'payan_readonly','target_fingerprint':'target-1','exact_scope_sha256':SH,'exact_scope':SCOPE,'implementation_source_sha256':SRC,'hostname':'example.com','pinned_addresses':['93.184.216.34'],'policy_evidence_sha256':'1'*64,'dns_evidence_sha256':'2'*64,'transport_contract_sha256':'3'*64,'transport_limits':limits,'max_network_requests':1,'execution_time_safety_revalidation_required':True,'execution_time_dns_pinning_anti_rebinding_revalidation_required':True,'credentials_allowed':False,'task_acceptance_enabled':False,'submission_enabled':False,'value_movement_enabled':False,'network_capable_adapter_reachable':False,'transport_enabled':False,'network_enabled':False,'network_calls_performed':False,'authorization_is_payment_or_task_permission':False,'authorization_is_execution_result':False}
a={**a0,'final_real_observation_authorization_sha256':H(a0)}
common={'target_fingerprint':'target-1','adapter_id':'payan_readonly','exact_scope_sha256':SH,'implementation_source_sha256':SRC}
po={**common,'mode':m.POL_MODE,'source_kind':'provider_first_party','source_ref':'https://example.com/policy','source_content_sha256':'5'*64,'observed_at':'2026-08-22T07:49:30Z','max_age_seconds':3600,'anonymous_read_only_get_allowed':True,'credentials_required':False,'automated_access_prohibited':False}; po={**po,'policy_evidence_sha256':H(po)}
d={**common,'mode':m.DNS_MODE,'source_kind':'system_probe','source_content_sha256':'6'*64,'observed_at':'2026-08-22T07:49:50Z','max_age_seconds':120,'hostname':'example.com','canonical_name':'example.com','aliases':[],'resolved_addresses':['93.184.216.34'],'pinned_addresses':['93.184.216.34'],'all_addresses_public':True,'alias_chain_checked':True,'rebinding_check_passed':True,'address_pinning_required':True}; d={**d,'dns_evidence_sha256':H(d)}
t={**common,'mode':m.TX_MODE,'hostname':'example.com',**limits,'reject_content_encoding_expansion_over_limit':True,'pin_resolved_addresses':True,'reuse_dns_after_connect':False}; t={**t,'transport_contract_sha256':H(t)}
def run(P=p,A=a,PO=po,D=d,T=t,prior=()): return m.consume_final_real_observation_authorization(P,A,policy_evidence=PO,dns_evidence=D,transport_contract=T,consumed_at=NOW,prior_consumption_receipt_sha256s=prior)
r=run(); assert not r['blockers'],r['blockers']; assert r['consumption_state'].endswith('ready_no_network'); assert r['network_calls_performed'] is False
rr=run(prior=[r['consumption_receipt']['final_real_observation_consumption_receipt_sha256']]); assert 'authorization_replay_detected' in rr['blockers']
A=copy.deepcopy(a); A['expires_at']='2026-08-22T07:49:59Z'; x=dict(A); x.pop('final_real_observation_authorization_sha256'); A['final_real_observation_authorization_sha256']=H(x); assert 'authorization_stale_or_not_yet_valid' in run(A=A)['blockers']
D=copy.deepcopy(d); D['resolved_addresses']=D['pinned_addresses']=['127.0.0.1']; x=dict(D);x.pop('dns_evidence_sha256');D['dns_evidence_sha256']=H(x); out=run(D=D); assert 'dns_resolution_contains_non_public_address' in out['blockers'] and 'dns_pinned_addresses_changed_since_packet' in out['blockers']
D=copy.deepcopy(d); D['hostname']='evil.example';D['canonical_name']='evil.example';x=dict(D);x.pop('dns_evidence_sha256');D['dns_evidence_sha256']=H(x); assert 'dns_hostname_changed_since_packet' in run(D=D)['blockers']
PO=copy.deepcopy(po); PO['observed_at']='2026-08-20T00:00:00Z';x=dict(PO);x.pop('policy_evidence_sha256');PO['policy_evidence_sha256']=H(x); assert 'policy_evidence_stale' in run(PO=PO)['blockers']
T=copy.deepcopy(t);T['allow_redirects']=True;x=dict(T);x.pop('transport_contract_sha256');T['transport_contract_sha256']=H(x); assert 'transport_contract_drift_from_packet' in run(T=T)['blockers']
P=copy.deepcopy(p);P['hostname']='other.example';assert 'packet_hash_invalid' in run(P=P)['blockers']
print('8 scenario checks passed')
